// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicPostCcxtFetchMarkets (params?: {}): Promise<implicitReturnType>;
    publicPostCcxtFetchCurrencies (params?: {}): Promise<implicitReturnType>;
    publicPostMarketCandleHistory (params?: {}): Promise<implicitReturnType>;
    publicPostMarketOrderbook (params?: {}): Promise<implicitReturnType>;
    publicPostMarketOrderbookPrice (params?: {}): Promise<implicitReturnType>;
    publicPostMarket24hrStats (params?: {}): Promise<implicitReturnType>;
    publicPostMarketTradeHistory (params?: {}): Promise<implicitReturnType>;
    privatePostAccountsPositions (params?: {}): Promise<implicitReturnType>;
    privatePostAccountsPositionLeverages (params?: {}): Promise<implicitReturnType>;
    privatePostAccountsOrderDatas (params?: {}): Promise<implicitReturnType>;
    privatePostAccountsCollateralHistory (params?: {}): Promise<implicitReturnType>;
    privatePostAccountsTradeHistory (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsCreateAccount (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsDepositCollateral (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsWithdrawCollateral (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsMarketOrder (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsLimitOrder (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsCancelOrders (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsReduceOrder (params?: {}): Promise<implicitReturnType>;
    privatePostTransactionsSetLeverage (params?: {}): Promise<implicitReturnType>;
    privatePostAccountSetPositionLeverage (params?: {}): Promise<implicitReturnType>;
    privatePostAccountSetPositionLeverageFromTx (params?: {}): Promise<implicitReturnType>;
    privatePostPreviewsPlaceOrder (params?: {}): Promise<implicitReturnType>;
    privatePostPreviewsCancelOrders (params?: {}): Promise<implicitReturnType>;
    privatePostPreviewsReduceOrder (params?: {}): Promise<implicitReturnType>;
    privatePostPreviewsSetLeverage (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
