import Exchange from './abstract/aftermath.js';
import { TICK_SIZE } from './base/functions/number.js';

export default class aftermath extends Exchange {
    describe () {
        return this.deepExtend (super.describe (), {
            'id': 'aftermath',
            'name': 'AftermathFinance',
            'countries': [ ],
            'version': 'v1',
            'rateLimit': 50, // 1200 requests per minute, 20 request per second
            'certified': false,
            'pro': false,
            'dex': true,
            'has': {
                'CORS': undefined,
                'spot': false,
                'margin': false,
                'swap': true,
                'future': false,
                'option': false,
                'cancelOrder': true,
                'cancelOrders': true,
                'createOrder': true,
                'editOrder': 'emulated',
                'fetchAccounts': false,
                'fetchBalance': true,
                'fetchCurrencies': true,
                'fetchDepositAddress': false,
                'fetchDeposits': true,
                'fetchFundingLimits': true,
                'fetchLedger': true,
                'fetchMarkets': true,
                'fetchMyTrades': true,
                'fetchOHLCV': true,
                'fetchOpenOrders': true,
                'fetchOrder': true,
                'fetchOrderBook': true,
                'fetchOrders': true,
                'fetchTicker': 'emulated',
                'fetchTrades': true,
                'fetchTradingFee': true,
                'fetchTradingFees': true,
                'fetchTradingLimits': 'emulated',
                'fetchTransactions': false,
                'fetchWithdrawals': true,
                'transfer': true,
                'withdraw': true,
            },
            'timeframes': {
                '1m': '1m',
                '3m': '3m',
                '5m': '5m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '2h': '2h',
                '4h': '4h',
                '8h': '8h',
                '12h': '12h',
                '1d': '1d',
                '3d': '3d',
                '1w': '1w',
                '1M': '1M',
            },
            'urls': {
                'logo': 'TODO',
                'api': 'https://staging-second.aftermath.finance/api/perpetuals',
                'www': 'https://www.aftermath.finance/',
                'doc': [
                    'TODO',
                ],
            },
            'api': {
                'public': {
                    'post': [
                        'all-markets',
                        'markets',
                        'market/candle-history',
                        'market/orderbook',
                        'market/orderbook-price',
                        'market/24hr-stats',
                        'market/trade-history',
                    ],
                },
                'private': {
                    'post': [
                        'accounts/positions',
                        'accounts/position-leverages',
                        'accounts/order-datas',
                        'accounts/collateral-history',
                        'accounts/trade-history',
                        'transactions/create-account',
                        'transactions/deposit-collateral',
                        'transactions/withdraw-collateral',
                        'transactions/market-order',
                        'transactions/limit-order',
                        'transactions/cancel-orders',
                        'transactions/reduce-order',
                        'transactions/set-leverage',
                        'account/set-position-leverage',
                        'account/set-position-leverage-from-tx',
                        'previews/place-order',
                        'previews/cancel-orders',
                        'previews/reduce-order',
                        'previews/set-leverage',
                    ],
                },
            },
            'requiredCredentials': {
                'apiKey': false,
                'secret': false,
                'walletAddress': true,
                'privateKey': true,
            },
            'precisionMode': TICK_SIZE,
            'options': {
                'defaultType': 'swap',
                'sandboxMode': false,
            },
        });
    }
}
